apiVersion: v1
kind: Service
metadata:
  name: log
  labels:
    app: log
    component: log
    type: stream-ats
    spring-deployment-id: log
spec:
  type: NodePort
  ports:
  - port: 80
    name: log-port
    targetPort: 8080
    protocol: TCP
  selector:
    app: log
    component: log
